# Generated by Django 4.0.2 on 2022-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookslibrarry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50, null=True)),
                ('book_author', models.CharField(max_length=10, null=True)),
                ('book_description', models.CharField(max_length=250, null=True)),
                ('book_issue_date', models.DateField(null=True)),
            ],
        ),
    ]
